;;;###autoload
(defun rwd-autohooks ()
  (interactive)
  (dolist (path (directory-files (concat user-init-dir "hooks") t ".*el$"))
    (let* ((mode          (file-name-nondirectory (file-name-sans-extension path)))
           (hook-name     (intern (concat mode "-hook")))
           (defun-name    (intern (concat "rwd-" mode "-hook")))
           (hook-path     (concat "hooks/" mode ".el"))
           (lisp          (read-file-to-string path)))
      (message "*** defining autohook: %s" defun-name)
      (eval (read (concat "(defun " (symbol-name defun-name) " () " lisp ")")))
      (and (functionp defun-name) 
           (remove-hook hook-name defun-name))
      (add-hook hook-name defun-name))))
