;;;###autoload
(defun rwd-autohooks ()
  (interactive)
  (dolist (path (directory-files (concat user-init-dir "hooks") t ".*el$"))
    (let* ((mode       (file-name-nondirectory (file-name-sans-extension path)))
           (hook-name  (intern (concat mode "-hook")))
           (raw-name   (concat "rwd-" mode "-hook"))
           (defun-name (intern raw-name))
           (lisp       (read-file-to-string path)))
      (eval (read (concat "(defun " raw-name " () " lisp ")")))
      (and (functionp defun-name)
           (remove-hook hook-name defun-name))
      (add-hook hook-name defun-name))))
