(defun rwd-load-modes ()
  (setq-local t1 (current-time))
  (require 'subr-x)
  (message "START: rwd-load-modes")
  (let* ((default-directory user-init-dir)
         (paths (file-expand-wildcards "./modes/*.el"))
         (clean (lambda (s) (string-remove-suffix ".el" s)))
         (names (mapcar clean paths)))
    (dolist (name names)
      (let ((t2 (current-time)))
        (load name nil t)
        (message "DONE: %-50S in %.2f sec" `(load ,name) (float-time (time-since t2))))))
  (message "DONE: %-50S in %.2f sec" "rwd-load-modes" (float-time (time-since t1))))

(provide 'rwd-load-modes)
